### ISSUE TITLE
NPM for everything

### ISSUE THREAD

**Issue by conor909** [alexbeletsky/alexbeletsky.github.io#8]
Contributions to this question are here: http://stackoverflow.com/questions/32127269/npm-scripts-nodemon-watching-js-and-scss-files-for-changes

http://beletsky.net/2015/04/npm-for-everything.html

Great tutorial, definitely will be using this process in the future.  One thing tho, the nodemon watch doesn't seem to work - is this deprecated?

If I remove the single quotes around the 'npm run build-sass' & 'npm run build-js' and use double quotes
`"watch-js": "nodemon -e js -w public/js -x \"npm run build-js\"" `
`"watch-sass": "nodemon -e scss -w public/sass -x \"npm run build-sass\"",`
it doesnt throw an error, but it doesn't trigger the commands

But if I keep it as is (in the tutorial) I get the following message in red writing 
`[nodemon] app crashed - waiting for file changes before restarting`
Its also doesn't trigger the commands

**Comment by conor909** [comment]
Ok so I fixed this, it might be worth sharing for anyone with the same issue.

When using windows there is the "The Windows Problem" - http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/#thewindowsproblem

I fixed it by installing parallelshell and changing my scripts from 
`"build": "npm run build-js & npm run build-sass",`
`"watch": "npm run watch-js & npm run watch-sass"`
to
`"build": "parallelshell \"npm run build-js\" \"npm run build-sass\""`
`"watch": "parallelshell \"npm run watch-js\" \"npm run watch-sass\""`

**Comment by alexbeletsky** [comment]
hey @conor909  exactly, the `&` won't work on windows, unfortunatelly. `paralleshell` seems like a great solution!

happy article helped you ;)
